### ISSUE TITLE
In develop branch, problem instantiating Csound and UI

### ISSUE THREAD

**Issue by jpcima** [rorywalsh/cabbage#55] opened 2019-08-29 01:07 UTC
Hi, I was able to disect the bug encountered and pictured at this comment, when run in Linux under Carla host.
https://github.com/T0NIT0RMX/ToneZ/issues/4#issuecomment-525904488

It's introduced by the single change at this commit: fefafd2

It's probably worth noting my sample rate is set at 48000.
When `prepareToPlay` is entered the first time, the condition `(sampleRate != samplingRate)` holds (having respective values 48000, 44100).

cabbage 3ac5fa81ca21f31901064f01988f28fd478c3bd2
carla-git 1:2.1.alpha2.r162.g8385b5ee-1

**Comment by rorywalsh** [comment] 2019-08-29 08:46
The issue I was trying to address there is the changing of sample rates while a plugin is loaded. it's caused me quite a lot of hardship. You should be able to reproduce the issue with the Cabbage host by changing the sample rate there during a session. it's best seen in the ModifyingWidgets examples from the Misc example menu. When sample rates are changed the Csound channels are no longer valid and the plugin GUI does not respond to messages from Csound. I'll take another look at resolving it. If you make any head in the mean time let me know. 

Thanks again for the input here. It's much appreciated 😉

**Comment by jpcima** [comment] 2019-08-31 11:53
Ok, does it mean DSP must inform UI a message "my Csound has changed, please synchronize yourself"? or it's more elaborate than that?
I'm not very familiar with the way how Csound works.

**Comment by rorywalsh** [comment] 2019-08-31 20:26
No, we just need to delete the old instance of Csound and create a new one, but something gets messed up along the way. The new instance works fine, but somehow the channels are messed up. I'm sure it can be resolved. I just need to find the time to do so.

**Comment by rorywalsh** [comment] 2019-09-02 16:11
Hi @jpcima. I've been trying to replicate your issues here on my Linux machine, but can't seem to do it. I also did some tests with the Cabbage plugin host and changing the sample rate there seems to work fine. Can you remove the if statement completely and see if that make a difference, so something like:

void CabbagePluginProcessor::prepareToPlay(double sampleRate, int samplesPerBlock) {
	
````if (sampleRate != samplingRate) {
        CsoundPluginProcessor::prepareToPlay(sampleRate, samplesPerBlock);
}```

**Comment by jpcima** [comment] 2019-09-03 19:56
About what I had to do to create the problem, it was to build the development branch, have the JACK server run the soundcard at 48 kHz instead of the default 44.1 of Cabbage, and load the VST version in a host with the ToneZ plugin.
I was busy with some tasks, but let's do this little check.

**Comment by jpcima** [comment] 2019-09-03 20:07
After rewriting `prepareToPlay` exactly as above, UI was exactly as broken as before, so it's no difference. I tried pulling latest develop and perform the test again, it was the same.

**Comment by rorywalsh** [comment] 2019-09-03 21:22
Thanks, I can recreate this issue now myself. It's interesting that it only
seems to be present on Linux, but at least I can recreate it now. Leave it
with me. I'll try to find a fix for it soon.

**Comment by rorywalsh** [comment] 2019-09-06 09:38
@jpcima, this should be fixed now. As you'll see from the commit I was failing to call a rather important method to rebind Csound channels to the plugin's parameters after changing the sampling rate and recompiling Csound. I'll leave the issue open until we get confirmation it works. I'm not at my Linux machine just now..

**Comment by rorywalsh** [comment] 2020-01-21 22:11
I'm going to close this out now. If there are still problem please reopen.

**Closed by rorywalsh** 2020-01-21 22:11 UTC
